name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installing libgtk2/3
      run: sudo apt install libgtk2.0-dev |            
           sudo apt install libgtk-3-dev
    - name: building app
      run: g++ *.cpp `wx-config --cxxflags --libs`
    - name: running app
      run: ./a.out
